name: Deploy FMS Angular Application to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ Checkout Source Code
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node.js & Angular CLI
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: ğŸ“¦ Install Dependencies
        run: npm install --legacy-peer-deps

      - name: ğŸ—ï¸ Build Angular Project
        run: npm run build

      - name: ğŸ³ Login to Docker Hub 
        run: echo "Cloudnexus@1234" | docker login -u "cloudansh" --password-stdin

      - name: ğŸ³ Build Docker Image
        run: docker build -t cloudansh/fms-system:latest .

      - name:  Push Docker Image to Docker Hub
        run: docker push cloudansh/fms-system:latest
      - name: ğŸ³ Docker Login on EC2
        run: echo "Cloudnexus@1234" | docker login -u "cloudansh" --password-stdin

      - name:  Pull Image from Docker Hub
        run: docker pull cloudansh/fms-system:latest

      - name: ğŸ—‘ï¸ Remove Old Container if exists
        run: docker rm -f fms-system-container || true

      - name: ğŸš€ Run New Container
        run: docker run -d -p 3000:80 --name fms-system-container cloudansh/fms-system:latest
